<?xml version="1.0" encoding="utf-8"?>
<doc>
    <assembly>
        <name>Spotlight.Switch</name>
    </assembly>
    
    <!-- GeometrySwitch Class -->

    <member name="Spotlight.Switch.GeometrySwitch.DSG__Point__RVT">
        <summary>
            Convert [Point] from {Autodesk Design Script Geometry} to {Revit XYZ}
        </summary>
        <param name="point_DSG">Autodesk.DesignScript.Geometry.Point</param>
        <returns name="xyz_RVT">Autodesk.Revit.DB.XYZ</returns>
    </member>
    
    <member name="Spotlight.Switch.GeometrySwitch.RVT__Point__DSG">
        <summary>
            Convert [Point] from {Revit XYZ} to {Autodesk Design Script Geometry}
        </summary>
        <param name="xyz_RVT">Autodesk.Revit.DB.XYZ</param>
        <returns name="point_DSG">Autodesk.DesignScript.Geometry.Point</returns>
    </member>

    <member name="Spotlight.Switch.GeometrySwitch.DSG__Curve__RVT">
        <summary>
            Convert [Curve] from {Autodesk Design Script Geometry} to {Revit XYZ}
        </summary>
        <param name="curve_DSG">Autodesk.DesignScript.Geometry.Curve</param>
        <returns name="curve_RVT">Autodesk.Revit.DB.Curve</returns>
    </member>

    <member name="Spotlight.Switch.GeometrySwitch.RVT__Curve__DSG">
        <summary>
            Convert [Curve] from {Revit XYZ} to {Autodesk Design Script Geometry}
        </summary>
        <param name="curve_RVT">Autodesk.Revit.DB.Curve</param>
        <returns name="curve_DSG">Autodesk.DesignScript.Geometry.Curve</returns>
    </member>
    
    <!-- ElementSwitch Class -->

    <member name="Spotlight.Switch.ElementSwitch.DYN__Wall__RVT">
        <summary>
            Convert [Wall] from {Dynamo Element} to {Revit Element}
        </summary>
        <param name="wall_DYN">Revit.Elements.Wall in RevitNodes.dll</param>
        <returns name="wall_RVT">Autodesk.Revit.DB.Wall</returns>
    </member>

    <member name="Spotlight.Switch.ElementSwitch.RVT__Wall__DYN">
        <summary>
            Convert [Wall] from {Revit Element} to {Dynamo Element}
        </summary>
        <param name="wall_RVT">Autodesk.Revit.DB.Wall</param>
        <returns name="wall_DYN">Revit.Elements.Wall in RevitNodes.dll</returns>
    </member>

    <member name="Spotlight.Switch.ElementSwitch.DYN__ModelCurve__RVT">
        <summary>
            Convert [Model Curve] from {Dynamo Element} to {Revit Element}
        </summary>
        <param name="modelCurve_DYN">Revit.Elements.ModelCurve in RevitNodes.dll</param>
        <returns name="modelCurve_RVT">Autodesk.Revit.DB.ModelCurve</returns>
    </member>

    <member name="Spotlight.Switch.ElementSwitch.DYN__ModelCurve__DSG">
        <summary>
            Convert [Model Curve] from {Dynamo Element} to {Autodesk Design Script Geometry}
        </summary>
        <param name="modelCurve_DYN">Revit.Elements.ModelCurve in RevitNodes.dll</param>
        <returns name="modelCurve_DSG">Autodesk.DesignScript.Geometry.Curve</returns>
    </member>
</doc>